# Generated by Django 3.1.7 on 2021-07-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20210419_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Each_Person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Hotel_For_Stay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Tour_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
