# Generated by Django 3.1.7 on 2021-07-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_auto_20210707_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Destination_place',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Tour_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
