# Generated by Django 3.1.7 on 2021-07-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_auto_20210707_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Tour_location',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Tour_name',
            new_name='name',
        ),
    ]
