# Generated by Django 3.1.7 on 2021-07-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_auto_20210707_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Tour_location',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Tour_name',
        ),
    ]
