# Generated by Django 3.1.7 on 2021-07-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_auto_20210707_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Destination_place',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Tour_name',
            new_name='name',
        ),
    ]
